typeset -gA ZSH_FEATURES

ZSH_FEATURES=(
  p10k                     1
  autosuggestions          1
  syntax-highlighting      1
  history-substring-search 1
)

# Run prehook local overrides.
[[ -f $ZDOTDIR/local/prehook.zsh ]] && source $ZDOTDIR/local/prehook.zsh || true

# Load core.
for file in $ZDOTDIR/core/*.zsh; do
  source "$file"
done

source $ZDOTDIR/prompt.simple.zsh

# Load extra features enabled in `local.zsh`.
for feature in ${(k)ZSH_FEATURES}; do
  [[ ${ZSH_FEATURES[$feature]} == 1 ]] && \
    source "$ZDOTDIR/features/$feature.zsh"
done

printf '\e[6 q'

# Run posthook local overrides.
[[ -f $ZDOTDIR/local/posthook.zsh ]] && source $ZDOTDIR/local/posthook.zsh || true
